"""Shared state schema for the recruitment pipeline.

All agents read from and write to this SharedState.
It acts as the central data structure for the orchestrator.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class PipelineStage(str, Enum):
    """Current stage of the recruitment pipeline."""
    INTAKE = "intake"
    JD_DRAFTING = "jd_drafting"
    JD_REVIEW = "jd_review"
    SOURCING = "sourcing"
    SCREENING = "screening"
    SHORTLIST_REVIEW = "shortlist_review"
    OUTREACH = "outreach"
    ENGAGEMENT = "engagement"
    SCHEDULING = "scheduling"
    INTERVIEWING = "interviewing"
    DECISION = "decision"
    HIRE_REVIEW = "hire_review"
    OFFER = "offer"
    COMPLETED = "completed"


class ApprovalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------

class CandidateProfile(BaseModel):
    """A candidate found by The Scout (Agent 3)."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    email: str = ""
    phone: str = ""
    skills: list[str] = Field(default_factory=list)
    experience_years: int = 0
    education: str = ""
    resume_text: str = ""
    source: str = "vector_search"
    relevance_score: float = 0.0
    match_reason: str = ""


class ScoredCandidate(BaseModel):
    """A candidate scored by The Screener (Agent 4)."""
    candidate_id: str
    candidate_name: str
    overall_score: float = 0.0  # 0-100
    skills_match: float = 0.0
    experience_match: float = 0.0
    education_match: float = 0.0
    cultural_fit: float = 0.0
    gaps: list[str] = Field(default_factory=list)
    strengths: list[str] = Field(default_factory=list)
    missing_skills: list[str] = Field(default_factory=list)
    overqualification: list[str] = Field(default_factory=list)
    reasoning: str = ""
    thought_process: str = ""
    match_percentage: float = 0.0


class Interview(BaseModel):
    """An interview scheduled by The Coordinator (Agent 5)."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    candidate_id: str
    candidate_name: str
    interview_type: str = "technical"  # technical, behavioral, cultural
    scheduled_time: str = ""
    duration_minutes: int = 60
    interviewers: list[str] = Field(default_factory=list)
    meeting_link: str = ""
    status: str = "scheduled"


class Assessment(BaseModel):
    """Competency assessment from The Interviewer (Agent 6)."""
    candidate_id: str
    candidate_name: str
    technical_score: float = 0.0   # 0-10
    communication_score: float = 0.0
    problem_solving_score: float = 0.0
    cultural_fit_score: float = 0.0
    overall_score: float = 0.0
    key_observations: list[str] = Field(default_factory=list)
    concerns: list[str] = Field(default_factory=list)
    transcript_summary: str = ""


class SuggestedQuestion(BaseModel):
    candidate_id: str
    candidate_name: str
    questions: list[str] = Field(default_factory=list)


class Recommendation(BaseModel):
    """Final recommendation from The Decider (Agent 7)."""
    candidate_id: str
    candidate_name: str
    decision: str = "no_hire"  # hire, no_hire, maybe
    confidence: float = 0.0  # 0-100
    screening_weight: float = 0.0
    interview_weight: float = 0.0
    overall_weighted_score: float = 0.0
    reasoning: str = ""
    risk_factors: list[str] = Field(default_factory=list)


class OutreachEmail(BaseModel):
    """Outreach email generated by Agent 5."""
    candidate_id: str
    candidate_name: str
    subject: str = ""
    body: str = ""
    status: str = "pending"  # pending | sent


class OfferRecord(BaseModel):
    """Offer letter generated by Agent 10."""
    candidate_id: str
    candidate_name: str
    offer_markdown: str = ""
    salary_offered: str = ""
    benefits_summary: str = ""
    valid_until: str = ""
    status: str = "draft"  # draft | sent | accepted | rejected


class AuditEntry(BaseModel):
    """An entry in the audit trail."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    agent: str
    action: str
    details: str = ""
    stage: str = ""


# ---------------------------------------------------------------------------
# Main Shared State (Pydantic BaseModel instead of TypedDict for strictness)
# ---------------------------------------------------------------------------

class SharedState(BaseModel):
    """Strictly validated shared state replacing the loose LangGraph TypedDict."""
    
    # --- Job Requisition (input) ---
    job_id: str = ""
    job_title: str = ""
    department: str = ""
    requirements: list[str] = Field(default_factory=list)
    preferred_qualifications: list[str] = Field(default_factory=list)
    location: str = "Remote"
    salary_range: str = "Competitive"

    # --- Agent 1: JD Architect output ---
    job_description: str = ""

    # --- Agent 2: Liaison HITL gates ---
    jd_approval: str = "pending"            # pending | approved | rejected
    shortlist_approval: str = "pending"     # pending | approved | rejected
    hire_approval: str = "pending"          # pending | approved | rejected
    human_feedback: str = ""                # free-text feedback from reviewer

    # --- Agent 3: Scout output ---
    candidates: list[CandidateProfile] = Field(default_factory=list)

    # --- Agent 4: Screener output ---
    scored_candidates: list[ScoredCandidate] = Field(default_factory=list)

    # --- Agent 5: Coordinator output ---
    scheduled_interviews: list[Interview] = Field(default_factory=list)

    # --- Agent 6: Interviewer output ---
    interview_assessments: list[Assessment] = Field(default_factory=list)
    interview_transcripts: list[str] = Field(default_factory=list)
    suggested_questions: list[SuggestedQuestion] = Field(default_factory=list)

    # --- Agent 7: Decider output ---
    final_recommendations: list[Recommendation] = Field(default_factory=list)

    # --- Agent 5 & 6: Outreach & Engagement ---
    outreach_emails: list[OutreachEmail] = Field(default_factory=list)
    candidate_responses: list[dict] = Field(default_factory=list)

    # --- Agent 10: Offer Generator ---
    offer_details: list[OfferRecord] = Field(default_factory=list)

    # --- Pipeline metadata ---
    current_stage: str = PipelineStage.INTAKE.value
    audit_log: list[AuditEntry] = Field(default_factory=list)
    error: str = ""

    def log_audit(self, agent: str, action: str, details: str, stage: str):
        self.audit_log.append(AuditEntry(
            agent=agent,
            action=action,
            details=details,
            stage=stage
        ))
